@startuml
title Online GraphML Editor
left to right direction

actor DataSpecialist as DS
actor UserCreator as UC

usecase EnterGraphs as "Enter graphs"
usecase SeeGraphs as "See graphs in real time"
usecase EditGraphObjects as "Edit/update graph objects"
usecase SaveProgress as "Save editing progress"
usecase PrepareGraphML as "GraphML file prep of XML outputs"

usecase DataEntry as "Data entry of graph edges and nodes"
usecase EditGraphObjects2 as "Editing of existing graph objects"
usecase RenderGraph as "Rendering of graph on the webpage"
usecase PrepareGraphMLContent as "Preparation of .GraphML files content"

usecase AddNodes as "Adding nodes"
usecase AddEdges as "Adding edges"
usecase EditNodesAndEdges as "Editing nodes and edges"

usecase AutomatedSaving as "Automated saving"
usecase GraphMerging as "Graph merging"

DS --> EnterGraphs
DS --> SeeGraphs
DS --> EditGraphObjects
DS --> SaveProgress
DS --> PrepareGraphML
DS --> DataEntry
DS --> EditGraphObjects2
DS --> RenderGraph
DS --> PrepareGraphMLContent
DS --> AddNodes
DS --> AddEdges
DS --> EditNodesAndEdges
DS --> AutomatedSaving
DS --> GraphMerging

UC --> EnterGraphs
UC --> SeeGraphs
UC --> EditGraphObjects
UC --> SaveProgress
UC --> PrepareGraphML
UC --> DataEntry
UC --> EditGraphObjects2
UC --> RenderGraph
UC --> PrepareGraphMLContent
UC --> AddNodes
UC --> AddEdges
UC --> EditNodesAndEdges
UC --> AutomatedSaving
UC --> GraphMerging

@enduml
